### ISSUE TITLE
Standardizing the way phone numbers are shown in the Wiki

### ISSUE THREAD

**Issue by icyflame** [metakgp/metakgp#3]
Currently, the phone numbers are rendered as so:

```
(03222) 282632
1 800 425 6633
9735551023
```

I would like to propose the following format for phone numbers:
1. Leading 0 be replaced by `(+91)` in all numbers. (0 dialing often leads to problems when calling from local / non-local numbers, etc. A `+91` dialing is automatically resolved, and is easier to use.)
2. A `-` between the STD code and the number in case of fixed lines.
3. Mobile numbers to be written as `123-456-4567`. 

In cases where the above is insufficient, follow [the national conventions for writing telephone numbers](https://en.wikipedia.org/wiki/National_conventions_for_writing_telephone_numbers#India)

**Arguments in favor**
1. Mobile numbers are easier to read off as three digit groups instead of a ten digit group, which is often unsettling.
2. When dialing from inside KGP, the long leading STD code can be dropped, and this would be easier to do if there were a clear distinction between the STD code and the number.
3. 0 dialing issues and [confusion regarding this](http://telecomtalk.info/full-mnp-india/136422/) can be avoided by simply using `+91` as the prefix.

---

Sample phone numbers:

```
(+91)-3222-282152
(+91)-123-456-7895
1-800-425-6633
```

---

cc @vivekiitkgp @hargup

**Comment by amrav** [comment]
+1 for standardising the way we write phone numbers. Thanks for raising this @icyflame. I suggest leaving out the dashes, for aesthetic reasons. Thus phone numbers would be rendered as: 

```
Landline: (+91) 3222 282152
Mobile: (+91) 123 456 7895
Special: 1 800 425 6633
```

If anyone else knows any national/international conventions for writing phone numbers, that would be useful to see.

**Comment by amrav** [comment]
Moved to https://wiki.metakgp.org/w/Metakgp_talk:Conventions, since:
- this isn't a site bug
- it would be useful to archive this discussion on the wiki rather than on Github, in order to understand in the future where these conventions came from
- other usability improvements are discussed on the wiki, and fragmenting these discussions over multiple sites will lead to headaches later
