### ISSUE TITLE
Unable to create account 

### ISSUE THREAD

**Issue by DefCon-007** [metakgp/metakgp#4]
While creating account it gives wrong or missing captcha error but in the account creation page there is no captcha

**Comment by amrav** [comment]
Temporary fix: hard refresh (Ctrl/Cmd+Shift+R) the page.

**Comment by OrkoHunter** [comment]
The issue has been resolved I guess. :)

**Comment by DefCon-007** [comment]
I guess we should not close it until we get a permanent fix for captcha

**Comment by OrkoHunter** [comment]
AFAIK the captcha has been replaced with new captcha.

**Comment by DefCon-007** [comment]
Ok. Cool . :)
