### ISSUE TITLE
Add a slack bot which will report github activity on slack

### ISSUE THREAD

**Issue by hargup** [metakgp/metakgp#6]

**Comment by OrkoHunter** [comment]
Added on #github channel. (Testing)

**Comment by OrkoHunter** [comment]
Well, I think only metakgp org owners can add that integration (receive payloads from github).

**Comment by hargup** [comment]
Owners of the github org or the slack org?

**Comment by raivivek** [comment]
Testing #github integration. Is this working?

**Comment by raivivek** [comment]
It's working.
